/*
 * Constants.c
 *
 *  Created on: Jul 26, 2009
 *      Author: ghaitho
 */

#include "Constants.h"

// FIXME: remove unused constants

int NOISE_RATE = 0;
float MIN_X = 0.0f;
float MIN_Y = 0.0f;
float MAX_X = 1000.0f;
float MAX_Y = 1000.0f;
float MIN_Z = 0.0f;
float MAX_Z = 10.0f;
float PROXIMITY_RADIUS = 1.0f;
float GOOD_VOXEL_SIZE = 2.0f;

int SIMULATOR_PRIORITY = 5;
int DETECTOR_STARTUP_PRIORITY = 20;
int DETECTOR_PRIORITY = 21;
long PERSISTENT_DETECTOR_SCOPE_SIZE = 10* 10 * 1000 * 1024;
long DETECTOR_PERIOD = 500;
long TRANSIENT_DETECTOR_SCOPE_SIZE = 10 * 10 * 1048576;

int MAX_FRAMES = 100;

int TIME_SCALE = 1;
int FPS = 50;
int BUFFER_FRAMES = 1000;
int PRESIMULATE = 0;
int SIMULATE_ONLY = 0;
char* DETECTOR_STATS = "detector.rin";
char* SIMULATOR_STATS = "simulator.rin";
char* DETECTOR_RELEASE_STATS = "release.rin";
//run a SPEC jvm98 benchmark to generate some noise
char* SPEC_NOISE_ARGS = "-a -b -g -s100 -m10 -M10 -t _213_javac";
int USE_SPEC_NOISE = 0;
int DETECTOR_NOISE_REACHABLE_POINTERS = 1000000;
int DETECTOR_NOISE_ALLOCATE_POINTERS = 10000;
int DETECTOR_NOISE_ALLOCATION_SIZE = 64;
int DETECTOR_NOISE_VARIABLE_ALLOCATION_SIZE = 0;
int DETECTOR_NOISE_ALLOCATION_SIZE_INCREMENT = 13;
int DETECTOR_NOISE_MIN_ALLOCATION_SIZE = 128;
int DETECTOR_NOISE_MAX_ALLOCATION_SIZE = 16384;
int DETECTOR_STARTUP_OFFSET_MILLIS = 3000;
int DETECTOR_NOISE = 0;
// write down the FRAMES into the frame.bin file
int FRAMES_BINARY_DUMP = 0;

// this is only for debugging of the detector code
//
// each frame generated by the simulator is processed exactly once by
// the detector ; this also turns on some debugging features
//
// the results thus should be deterministic
int SYNCHRONOUS_DETECTOR = 0;

int DUMP_RECEIVED_FRAMES = 0;
int DUMP_SENT_FRAMES = 0;
int DEBUG_DETECTOR = 0;
